## buildstep base image
FROM balenalib/fincm3-debian:buster-build

WORKDIR /usr/src/app

## install required packages
RUN apt-get update && apt-get install -yq --no-install-recommends \
  libusb-1.0-0 \
  libusb-1.0-0-dev \
  libudev-dev

RUN git clone https://github.com/mvp/uhubctl && cd uhubctl && make -j 16

RUN tar -czf uhubctl.tar.gz /usr/src/app/uhubctl

COPY ./start.sh ./

CMD ["bash", "/usr/src/app/start.sh"]
